defmodule Nixploy.Deployments.ProjectCredentialsTest do
  use ExUnit.Case, async: true

  alias Nixploy.Deployments.ProjectCredentials
  alias Nixploy.Execution.Result

  test "parses a strict bounded dotenv subset without exposing line contents in errors" do
    assert {:ok, secrets} =
             ProjectCredentials.parse_dotenv("""
             # generated by sops
             export DATABASE_URL="postgres://db/app?ssl=true"
             API_TOKEN='token value'
             ESCAPED="line\\nvalue"
             """)

    assert secrets == [
             %{name: "API_TOKEN", value: "token value"},
             %{name: "DATABASE_URL", value: "postgres://db/app?ssl=true"},
             %{name: "ESCAPED", value: "line\nvalue"}
           ]

    assert {:error, {:invalid_dotenv_line, 1}} =
             ProjectCredentials.parse_dotenv("not-an-assignment-with-sensitive-content")

    assert {:error, {:duplicate_credential, "TOKEN"}} =
             ProjectCredentials.parse_dotenv("TOKEN=first\nTOKEN=second")

    assert {:error, {:invalid_dotenv_line, 1}} = ProjectCredentials.parse_dotenv("EMPTY=")
  end

  test "decrypts only in a worker process with fixed bounded sops argv" do
    parent = self()

    execute = fn command, opts ->
      send(parent, {:command, command, opts})

      output =
        case command.executable do
          "ssh-to-age" -> "AGE-SECRET-KEY-1FIXTUREIDENTITY\n"
          "sops" -> "TOKEN=worker-only-value\n"
        end

      {:ok, %Result{exit_status: 0, output_tail: output, output_truncated?: false}}
    end

    assert {:ok, [%{name: "TOKEN", value: "worker-only-value"}]} =
             ProjectCredentials.resolve(
               %{"app" => "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-secret.env"},
               execute: execute,
               identity_file: "/run/credentials/worker/ssh-key",
               path_exists?: fn _path -> true end,
               worker?: fn -> true end
             )

    assert_receive {:command, identity_command, []}
    assert identity_command.executable == "ssh-to-age"
    assert identity_command.args == ["-private-key", "-i", "/run/credentials/worker/ssh-key"]
    assert identity_command.timeout == 30_000
    assert identity_command.max_output_bytes == 4_096

    assert_receive {:command, command, []}
    assert command.executable == "sops"

    assert command.args == [
             "decrypt",
             "--input-type",
             "dotenv",
             "--output-type",
             "dotenv",
             "--",
             "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-secret.env"
           ]

    assert command.env == %{"SOPS_AGE_KEY" => "AGE-SECRET-KEY-1FIXTUREIDENTITY"}
    assert command.redact == ["AGE-SECRET-KEY-1FIXTUREIDENTITY"]
    assert command.timeout == 60_000
    assert command.max_output_bytes == 262_144
    refute inspect(command) =~ "worker-only-value"
  end

  test "fails before decryption outside the dedicated worker role" do
    assert {:error, :credential_worker_required} =
             ProjectCredentials.resolve(
               %{"app" => "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-secret.env"},
               identity_file: "/run/credentials/web/ssh-key",
               path_exists?: fn _path -> true end,
               worker?: fn -> false end,
               execute: fn _command, _opts -> flunk("web process attempted decryption") end
             )
  end

  test "does not retain sops diagnostics when decryption fails" do
    assert {:error, {:credential_decryption_failed, "app"}} =
             ProjectCredentials.resolve(
               %{"app" => "/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-secret.env"},
               identity_file: "/run/credentials/worker/ssh-key",
               path_exists?: fn _path -> true end,
               worker?: fn -> true end,
               execute: fn command, _opts ->
                 if command.executable == "ssh-to-age" do
                   {:ok,
                    %Result{
                      exit_status: 0,
                      output_tail: "AGE-SECRET-KEY-1FIXTUREIDENTITY\n",
                      output_truncated?: false
                    }}
                 else
                   {:ok,
                    %Result{
                      exit_status: 1,
                      output_tail: "sensitive provider diagnostic",
                      output_truncated?: false
                    }}
                 end
               end
             )
  end
end
