(library
 (name core_test)
 (modules core_test)
 (libraries nixploy core)
 (inline_tests)
 (preprocess
  (pps ppx_jane)))

(test
 (name application_test)
 (modules application_test)
 (libraries nixploy core core_unix.command_unix async)
 (preprocess
  (pps ppx_jane)))

(test
 (name consumer_mapping_test)
 (modules consumer_mapping_test)
 (libraries nixploy nixploy_cli_mapping nixploy_rpc_mapping core)
 (preprocess
  (pps ppx_jane)))

(test
 (name process_runner_test)
 (modules process_runner_test)
 (libraries nixploy core core_unix.command_unix async)
 (preprocess
  (pps ppx_jane)))

(test
 (name store_test)
 (modules store_test)
 (libraries nixploy core core_unix.command_unix async)
 (preprocess
  (pps ppx_jane)))

(test
 (name source_test)
 (modules source_test)
 (libraries nixploy core core_unix.command_unix async)
 (preprocess
  (pps ppx_jane)))

(executable
 (name rpc_probe)
 (modules rpc_probe)
 (libraries async async_rpc_websocket core core_unix.command_unix protocol)
 (preprocess
  (pps ppx_jane)))
