import Config

# Configure your database. The default keeps plain `mix` commands convenient,
# while the SOPS-backed Justfile can supply the complete connection URL.
database_url =
  System.get_env("DATABASE_URL", "ecto://postgres:postgres@localhost/nixploy_dev")

config :nixploy, Nixploy.Repo,
  url: database_url,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE", "10"))

external_scheme =
  case System.get_env("PHX_SCHEME", "http") do
    scheme when scheme in ["http", "https"] -> scheme
    invalid -> raise "invalid PHX_SCHEME #{inspect(invalid)}; expected http or https"
  end

external_host = System.get_env("PHX_HOST", "localhost")

external_port =
  System.get_env(
    "PHX_URL_PORT",
    if(external_scheme == "https", do: "443", else: System.get_env("PORT", "4000"))
  )
  |> String.to_integer()

# Development is accessed exclusively through the Tailscale HTTPS proxy.
# Keep this compile-time session setting stable across plain Mix commands and
# `just dev`, which loads the external URL variables from SOPS.
config :nixploy, secure_cookies: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nixploy, NixployWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  url: [scheme: external_scheme, host: external_host, port: external_port],
  check_origin: true,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env(
      "SECRET_KEY_BASE",
      "hU3drq4zPRHTW/43XS4wIG0myuenKVSjbSL7XAbZaKrEzAWr0VpUD4y+DyG3Zw4r"
    ),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:nixploy, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:nixploy, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :nixploy, NixployWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/nixploy_web/router\.ex$",
      ~r"lib/nixploy_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :nixploy, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
